name: Delete old workflow runs
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_dispatch: {}

# Disable permissions for all available scopes
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  delete-workflow-run:
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@0073229620e676f1b9d933b31b2b53df8b5915ef # v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 90
          keep_minimum_runs: 14
