name: Drift Detection

on:
  schedule:
    - cron: 0 */8 * * 1-5 # Every 8 Hours on weekdays
  workflow_dispatch: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  drift-detection:
    name: Drift Detection
    runs-on: ubuntu-latest
    permissions:
      actions: read # Required to download repository artifact.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      issues: write # Required to add drift detection issues.
      pull-requests: write # Required to add PR comment and label.
    environment: development
    env:
      TF_TOKEN_APP_TERRAFORM_IO: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_DEV_OIDC_ROLE_ARN }}
          role-session-name: gitops2024-development-terraform-deploy

      - name: Terraform Plan
        uses: devsectop/tf-via-pr@f1acaae1d94826457fa57bc65f1df318fd81b3bc # v12.0.0
        id: drift-plan
        with:
          working-directory: terraform/development
          command: plan
          hide-args: true
          plan-encrypt: ${{ secrets.PGP_SECRET_SIGNING_PASSPHRASE }}

      - name: Create Drift Issue
        if: ${{ steps.drift-plan.outputs.exitcode == 2 }}
        uses: dacbd/create-issue-action@cdb57ab6ff8862aa09fee2be6ba77a59581921c2 # v2.0.0
        with:
          token: ${{ github.token }}
          title: Configuration ${{ github.workflow }}
          body: |

            <details><summary>Diff of changes.</summary>

            ```diff
            ${{ steps.drift-plan.outputs.diff }}
            ```
            </details>

            <details><summary>${{ steps.drift-plan.outputs.summary }}</summary>

            ```hcl
            ${{ steps.drift-plan.outputs.result }}
            ```

            </details>

            [View run log.](${{ steps.drift-plan.outputs.run-url }})

          labels: tf:diff
