name: IAC Deploy
run-name: ${{ github.event_name == 'merge_group' && github.event.merge_group.head_commit.message || ''}}

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]
  merge_group:
    types: [checks_requested]

permissions: {}

jobs:
  deploy-dev:
    name: Deploy to Development Environment
    permissions:
      actions: read
      checks: write
      contents: read
      id-token: write
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/iac-deploy.yaml@8ecdd703d6706fee10ec0dce5fa4066d967b634c # v4.21.0
    secrets: inherit
    with:
      environment: development
