name: PR Check
run-name: ${{ github.event_name == 'merge_group' && github.event.merge_group.head_commit.message || ''}}

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  merge_group:
    types: [checks_requested]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Validate PR title
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@cb34180fdd9af5c0609d7fa46f31d00f338bd9db # v4.19.1

  dependency-review:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/dependency-review.yaml@cb34180fdd9af5c0609d7fa46f31d00f338bd9db # v4.19.1

  enforce-all-checks:
    name: Checks
    permissions:
      checks: read
    uses: 3ware/workflows/.github/workflows/wait-for-checks.yaml@cb34180fdd9af5c0609d7fa46f31d00f338bd9db # v4.19.1
    secrets: inherit
