name: PR Check
on:
  pull_request:
    types: [opened, edited]

# Disable permissions for all available scopes
permissions: {}

jobs:
  convert-to-draft:
    name: Mark as draft
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Mark as draft
        uses: voiceflow/draft-pr@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  validate-pr-title:
    name: Validate PR title
    permissions:
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@7880d6b986d1d689f5d219e901b863f1378fea9c # v4.4.0
