name: PR Check
on:
  pull_request:
    types: [opened, edited]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    name: Validate PR title
    permissions:
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@fbeb3bb506c61e0d263c6b7dd4cb57c76923001b # v4.14.0
