name: PR Check
run-name: ${{ github.event_name == 'merge_group' && github.event.merge_group.head_commit.message || ''}}

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
    branches: [main]
  merge_group:
    types: [checks_requested]

# Disable permissions for all available scopes
permissions: {}

jobs:
  validate-pr-title:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Validate PR title
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/pr-title.yaml@a382d8b5c5f0da96221eb0160cd755b347886eca # v4.20.0

  dependency-review:
    if: ${{ github.event_name == 'pull_request_target' }}
    name: Dependency Review
    permissions:
      contents: read
      pull-requests: write
    uses: 3ware/workflows/.github/workflows/dependency-review.yaml@a382d8b5c5f0da96221eb0160cd755b347886eca # v4.20.0

  enforce-all-checks:
    name: Checks
    permissions:
      checks: read
    uses: 3ware/workflows/.github/workflows/wait-for-checks.yaml@a382d8b5c5f0da96221eb0160cd755b347886eca # v4.20.0
    secrets: inherit
