name: Release
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: [Terraform Docs]
    types: [completed]

# Disable permissions for all available scopes
permissions: {}

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    uses: 3ware/workflows/.github/workflows/release.yaml@2f083d4e6080eb25ffbd5793a09cd85ac5bb9598 # v4.21.5
    secrets: inherit
