name: Release
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: [Terraform Docs]
    types: [completed]

# Disable permissions for all available scopes
permissions: {}

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    uses: 3ware/workflows/.github/workflows/release.yaml@7a3e4ea551868a1f4e1cd69ce25c0a3ca8b5e0db # v4.20.1
    secrets: inherit
