name: Release
run-name: ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: [Terraform Docs]
    types: [completed]

# Disable permissions for all available scopes
permissions: {}

jobs:
  semantic-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    uses: 3ware/workflows/.github/workflows/release.yaml@8ecdd703d6706fee10ec0dce5fa4066d967b634c # v4.21.0
    secrets: inherit
