name: Terraform Docs

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - iac/**/*.tf
      - iac/**/*.tfvars
      - iac/**/*.tftpl
      - iac/**/*.hcl

# Disable permissions for all available scopes
permissions: {}

jobs:
  terraform-docs:
    if: ${{ github.event.pull_request.merged == true }}
    name: Terraform Docs
    uses: 3ware/workflows/.github/workflows/terraform-docs.yaml@734372a063bf29df3dd2e04315dfad6698248eea # v4.21.1
    secrets: inherit
    with:
      tf-directory: terraform
