name: Terraform Docs

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - terraform/**/*.tf
      - terraform/**/*.tfvars
      - terraform/**/*.tftpl

# Disable permissions for all available scopes
permissions: {}

jobs:
  terraform-docs:
    if: ${{ github.event.pull_request.merged == true }}
    name: Terraform Docs
    uses: 3ware/workflows/.github/workflows/terraform-docs.yaml@fbeb3bb506c61e0d263c6b7dd4cb57c76923001b # v4.14.0
    secrets: inherit
    with:
      tf-directory: terraform
