name: Trunk Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.tf"
      - "**/*.tfvars"

# Disable permissions for all available scopes.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Trunk Check
        uses: trunk-io/trunk-action@0c109cf103b1bf745bb0cd8ec19d00a4609527d8 # v1.1.17
        with:
          arguments: --filter -tflint,-terraform
