name: Trunk Check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - "**/*.tf"
      - "**/*.tfvars"

# Disable permissions for all available scopes.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Trunk Check
        uses: trunk-io/trunk-action@12da16fcdd5cad1903d0082e591e09df7b67c7f0 # v1.1.17
        with:
          arguments: --filter -tflint,-terraform
